In [1]:
import numpy as np

def func(x, y):
    return np.sin(y * x)

xaxis = np.linspace(0, 4, 10)
yaxis = np.linspace(-1, 1, 20)
result = func(xaxis[:,None], yaxis[None,:])

In [2]:
result

array([[-0.        , -0.        , -0.        , -0.        , -0.        ,
        -0.        , -0.        , -0.        , -0.        , -0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.42995636, -0.38726275, -0.34372169, -0.29942845, -0.25447998,
        -0.20897462, -0.16301197, -0.11669259, -0.07011786, -0.02338968,
         0.02338968,  0.07011786,  0.11669259,  0.16301197,  0.20897462,
         0.25447998,  0.29942845,  0.34372169,  0.38726275,  0.42995636],
       [-0.77637192, -0.71408881, -0.64555852, -0.57138061, -0.492204  ,
        -0.40872137, -0.32166307, -0.23179071, -0.13989055, -0.04676656,
         0.04676656,  0.13989055,  0.23179071,  0.32166307,  0.40872137,
         0.492204  ,  0.57138061,  0.64555852,  0.71408881,  0.77637192],
       [-0.9719379 , -0.9294733 , -0.86872962, -0.79090146, -0.69751938,
        -0.59041986, -0.4717091 , -0.34372169, -

In [3]:
xaxis

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [4]:
foo(np.arange(9).reshape(3,3), np.arange(9).reshape(3,3))

NameError: name 'foo' is not defined

In [20]:
x = np.arange(16).reshape(4,4)

In [27]:
x[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [25]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.split(x, (2,2))

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([], shape=(0, 4), dtype=int64),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [14]:
print(range(0,10,2))

range(0, 10, 2)


In [16]:
for i in range(0, 10, 2):
...     print(i)

0
2
4
6
8


In [38]:
h, w = (4,4)
h_step, w_step = (1,1)
h_len, w_len = (2,2)
for i in range(0, h-h_len+1, h_step):
    for j in range(0, w-w_len+1, w_step):
        print(i,j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [33]:
x = np.arange(12).reshape(3,4, order='F')

In [34]:
x

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [36]:
x[:,:2]

array([[0, 3],
       [1, 4],
       [2, 5]])

In [44]:
x = np.array([[1, 2],[1,2]])

print(x.shape)  # prints (2,)
#Then

y = np.expand_dims(x, axis=2)

(2, 2)


In [46]:
y.shape

(2, 2, 1)